### ISSUE TITLE
install/easy-docker-install.sh is missed

### ISSUE THREAD

**Issue by genestack-solomatin** [curoverse/arvados-dev#7]
Hi, your [documentation](https://doc.arvados.org/install/pre-built-docker.html) references: [get.arvados.org](get.arvados.org) which should redirect to https://raw.githubusercontent.com/curoverse/arvados-dev/master/install/easy-docker-install.sh

But this script not in the repo.  

Please sync documentation and the repository content.

**Comment by cure** [comment]
Thanks for reporting this; the docker install method was replaced with Docker, see https://doc.arvados.org/install/arvbox.html
